### ISSUE TITLE
Deploying OpenTelemetry Collector, Jaeger, and Prometheus with Docker Compose for Observability

### ISSUE THREAD

**Issue by horw** [blackhorseya/godine#79]
Hello!
I have read your article about OpenTelemetry on Medium (https://medium.com/@blackhorseya/deploying-opentelemetry-collector-jaeger-and-prometheus-with-docker-compose-for-observability-fedd7c0898b5) and noticed some small changes that can be made:
```
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "9090:9090" # Prometheus exporter port  <- here
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans
      - "4317:4317" # OTLP gRPC receiver for jaeger <- here
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090
   ```
Please note that ports do not need to be mapped, otherwise, it will not start.
